### ISSUE TITLE
problem with progress output

### ISSUE THREAD

**Issue by stax76** [OpenVisualCloud/SVT-AV1#1348]
The progress is written without line breaks, this is very unfortunate for programmers that don't have much experience, I needed a full day to replace a complex component:

Before:

https://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/AsyncStreamReader.cs

After:

https://github.com/staxrip/staxrip/blob/master/General/AsyncStreamReader.vb

staxrip supports 200 tools and is 18 years old, it's the first console tools I've seen writing progress like this.

staxrip works now using the ms compiler for building your encoder but with GCC there is again an issue with the progress output, it's different so staxrip can't show proper progress.

I would guess it has something to do with text encoding, unfortunately I've not really time to investigate it.

**Comment by 1480c1** [comment]
The main reason why is because we use backspace, often resulting in broken output, rather than carriage returns or newlines or both

```c
fprintf(stderr, "\b\b\b\b\b\b\b\b\b%9d", frame_count);
```

**Comment by stax76** [comment]
This line has only ASCII characters, I don't see why a GCC build outputs something different from a MSVC build.

There is something different with flush occurrence/timing.

**Comment by 1480c1** [comment]
Perhaps because of the `fflush(stdout);` right after?

Just making sure, when you say `GCC`, do you mean mingw-w64 gcc for windows, or gcc for *nix?

**Comment by stax76** [comment]
Patman builds many tools for staxrip, I think he uses something like media autobuild suite, so yes I think Mingw-w64.

**Comment by Patman86** [comment]
I confirm, that happens when I'm using gcc in msys2 (mingw-w64).

**Comment by 1480c1** [comment]
@stax76, do you know if your executable update detection handling supports detection on carriage returns (`\r`)?

I see https://github.com/staxrip/staxrip/blob/master/General/AsyncStreamReader.vb#L91 and https://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/AsyncStreamReader.cs,230 but I do not know enough about C# to be able to read it competently.

I currently am working on changing the line from backspace to a carriage return here https://github.com/1480c1/SVT-AV1/tree/progressoutput , but am not sure if this will actually solve your issue.

**Comment by stax76** [comment]
The original from Microsoft generates an event for \r and \n and my enhancement additionally for \b.

I assume that if you use \r or \n then this will automatically trigger flush and the GCC problem is solved, I will have to do some adjustment but it's very unlikely that it will be difficult.

Thanks for working on it.

**Comment by 1480c1** [comment]
Okay, I will try to open a PR about it then, thanks

**Comment by Patman86** [comment]
I compiled SVT-AV1 again with gcc and the problem still persists.

**Comment by 1480c1** [comment]
The pr hasn't been merged

**Comment by stax76** [comment]
Thanks for fixing it. [Same problem with aomenc now](https://bugs.chromium.org/p/aomedia/issues/detail?id=2909). 🤔
