### ISSUE TITLE
Segfaults after merging PR #333 

### ISSUE THREAD

**Issue by mafonsoN** [OpenVisualCloud/SVT-AV1#346]
Encoding modes > 0 are crashing on Mac in the SIMD functions. Reverted back to commit 2f72785, just before #333 was merged and it seems to be working fine, so guessing this introduced the problem?

Example command line:

./SvtAv1EncApp -i speed_bag_640x360_60f.yuv -w 640 -h 360 -fps-num 50000 -fps-denom 1000 -q 63 -n 60 -b speed_bag_640x360_60f_svtav1_cq63.ivf -o speed_bag_640x360_60f_svtav1_cq63.yuv -intra-period 119 -bit-depth 8 -enc-mode 5

Error: 

EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

Call stack: 
yy_loadu_256 synonyms_avx2.h:31
cross_sum_fast_even_row selfguided_avx2.c:438
final_filter_fast selfguided_avx2.c:511

**Comment by hassount** [comment]
@mafonsoN thank you for reporting this.
it's weird how the CI actually passed while testing -enc-mode 8 :/

**Comment by 1480c1** [comment]
Probably because the macOS vms did not have a avx2 CPU so it did not use the avx2 functions

**Comment by mafonsoN** [comment]
> @mafonsoN thank you for reporting this.
> it's weird how the CI actually passed while testing -enc-mode 8 :/

Actually, enc-mode 8 is the only one working on my tests :).

**Comment by hassount** [comment]
gotcha, then the wiener filter opt is a good suspect. then @1480c1 question is accurate, do you have avx2 supported on your machine?

**Comment by mafonsoN** [comment]
> Probably because the macOS vms did not have a avx2 CPU so it did not use the avx2 functions
> […](#)
> On Jun 7, 2019, at 2:55 PM, Hassene Tmar ***@***.***> wrote: @mafonsoN thank you for reporting this. it's weird how the CI actually passed while testing -enc-mode 8 :/ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.



> gotcha, then the wiener filter opt is a good suspect. then @1480c1 question is accurate, do you have avx2 supported on your machine?


Yes, I have. I'm running it on my Macbook Pro.

**Comment by lzhangnj** [comment]
@mafonsoN Thanks for reporting the bug. When I ran unit test "./SvtAv1UnitTests --gtest_filter=*EbRestorationPick.*" on my Macbook Pro, the new AVX2 optimization of Weiner Filter cannot pass all of it. I fixed the bug and now it passed the unit test. Sorry that the yuv encoding test on my Macbook pro crashes somewhere else so I have to rely on you to help verify my fix "Fix a couple of bugs in Wiener Filter AVX2" as shown in above commit ca14030 notice. If you could apply the fix to OpenVisualCloud/SVT-AV1:master and rerun your encoding, that would be awesome. Thanks a lot!

**Comment by lzhangnj** [comment]
The bug I fixed is an out of bounds writing to an array __m256i deltas[], which was caught by MAC compiler. The compiler in Windows and Linux may treat the bug differently, so it only exposes on MAC. Let's see if this bug is the reason of this issue.

**Comment by mafonsoN** [comment]
> @mafonsoN Thanks for reporting the bug. When I ran unit test "./SvtAv1UnitTests --gtest_filter=_EbRestorationPick._" on my Macbook Pro, the new AVX2 optimization of Weiner Filter cannot pass all of it. I fixed the bug and now it passed the unit test. Sorry that the yuv encoding test on my Macbook pro crashes somewhere else so I have to rely on you to help verify my fix "Fix a couple of bugs in Wiener Filter AVX2" as shown in above commit [ca14030](https://github.com/OpenVisualCloud/SVT-AV1/commit/ca14030c0de3de94baea6e504dbd8811f9316d0a) notice. If you could apply the fix to OpenVisualCloud/SVT-AV1:master and rerun your encoding, that would be awesome. Thanks a lot!

Still getting the crash on your branch. Are you able to reproduce the problem?

**Comment by lzhangnj** [comment]
When I ran "./SvtAv1EncApp -i ../../test/vectors/niklas_640_480_30.yuv -w 640 -h 360 -fps-num 50000 -fps-denom 1000 -q 63 -n 60 -b t.ivf -o t.yuv -intra-period 119 -bit-depth 8 -enc-mode 5" on my Macbook Pro, I got "Could not allocate enough memory for channel 1". So the encoder crashes earlier. Sorry that I cannot reproduce the problem.

My configuration is:

-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- The ASM_NASM compiler identification is YASM
-- Found assembler: /usr/local/bin/yasm

$ yasm --version
yasm 1.3.0
Compiled on Oct 14 2018.

**Comment by 1480c1** [comment]
https://github.com/OpenVisualCloud/SVT-AV1/blob/master/README.md#linux-operating-systems-64-bit
Note about MacOS

Can you see if that is related?

**Comment by lzhangnj** [comment]
Thanks and I switched from clang to gcc 9.1.0, after fixing some other compiling errors, I still got the same error.

What exact tool chains are you using? Thanks!

-------------------------------------------
SVT-AV1 Encoder
SVT [version]:	SVT-AV1 Encoder Lib v0.5.0
SVT [build]  :	GCC 9.1.0	 64 bit
LIB Build date: Jun  8 2019 22:19:05
-------------------------------------------
Number of logical cores available: 12
Number of PPCS 89
------------------------------------------- 
SVT [config]: Main Profile	Tier (auto)	Level (auto)	
SVT [config]: EncoderMode 							: 0 
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat	: 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight					: 640 / 360 
SVT [config]: Fps_Numerator / Fps_Denominator / Gop Size / IntraRefreshType 	: 50000 / 1000 / 120 / 1
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure		: 4 / 0 / 2 
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange			: CQP / 63 / 33 / 0 
------------------------------------------- 
errno: 24
Encoding          
Could not allocate enough memory for channel 1
Encoder finished

**Comment by mafonsoN** [comment]
For me, the error you are reporting only happens one in a while and is a semaphore issue according to #178. 

My system is:

-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- The ASM_NASM compiler identification is YASM
-- Found assembler: /usr/local/bin/yasm
-- Check for working C compiler: /usr/bin/gcc

$ yasm --version
yasm 1.3.0

**Comment by lzhangnj** [comment]
@mafonsoN @1480c1 Thanks for the solution. I can reproduce the segfaults after running "ulimit -n 1000".

It's weird that the bug is caused by creating 2 big arrays in av1_compute_stats_avx2(), with total size 384K bytes. To fix it, I have to call malloc and free for MAC OS to work around.

I don't have an explanation for this. Do you know is there any memory/stack limits in function level for MAC OS in this application?

**Comment by mafonsoN** [comment]
@lzhangnj I believe the stack can be checked using ulimit -a:

$ ulimit -a | grep stack
stack size              (kbytes, -s) 8192

So, 8 MB. 

The size you mention is lower than that, so it seems strange that it is the source of the problem. 

Could you create a PR to fix this issue?

**Comment by lzhangnj** [comment]
Thanks! The buffer size is 768K bytes. How many instances of Weiner filter would be created in multi-threading? I enlarged stack limit to 32 MB but still got segfaults.

**Comment by mafonsoN** [comment]
@hassount can you advise about this?

**Comment by hassount** [comment]
@mafonsoN isn't #354 addressing this ?

**Comment by mafonsoN** [comment]
@hassount that wasn't my prior understanding but I did some quick tests with PR #354 and there were no crashes.

**Comment by hassount** [comment]
@mafonsoN so can we close this issue ?

**Comment by hassount** [comment]
@mafonsoN can we close this issue ?
