### ISSUE TITLE
Mismatch issue in wiener convolve unit test

### ISSUE THREAD

**Issue by Cidana-Developers** [OpenVisualCloud/SVT-AV1#547]
Step to reproduce:
`./SvtAv1UnitTests --gtest_filter="*WienerConvolve*"`

console output:
```
Running main() from /Users/yons/work/SVT-AV1/third_party/googletest/src/gtest_main.cc
Note: Google Test filter = *WienerConvolve*
[==========] Running 23 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 14 tests from AV1/AV1WienerConvolveLbdTest
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/0
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: 'z' (122, 0x7A)
  output_ref_[j]
    Which is: 'y' (121, 0x79)
Pixel mismatch at index 11 = (3, 1)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/0, where GetParam() = (8, 8, 0x107dab140) (1 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/1
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\xA7' (167)
  output_ref_[j]
    Which is: '\xA8' (168)
Pixel mismatch at index 21 = (5, 2)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/1, where GetParam() = (8, 4, 0x107dab140) (15 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/2
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\xBF' (191)
  output_ref_[j]
    Which is: '\xBE' (190)
Pixel mismatch at index 73 = (9, 1)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/2, where GetParam() = (64, 24, 0x107dab140) (0 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/3
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\xFB' (251)
  output_ref_[j]
    Which is: '\xFA' (250)
Pixel mismatch at index 819 = (51, 12)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/3, where GetParam() = (64, 64, 0x107dab140) (0 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/4
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\x8C' (140)
  output_ref_[j]
    Which is: '\x8D' (141)
Pixel mismatch at index 376 = (56, 5)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/4, where GetParam() = (64, 56, 0x107dab140) (1 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/5
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\xC5' (197)
  output_ref_[j]
    Which is: '\xC3' (195)
Pixel mismatch at index 11 = (11, 0)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/5, where GetParam() = (32, 8, 0x107dab140) (0 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/6
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\xF6' (246)
  output_ref_[j]
    Which is: '\xF5' (245)
Pixel mismatch at index 448 = (0, 14)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/6, where GetParam() = (32, 28, 0x107dab140) (1 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/7
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\xF6' (246)
  output_ref_[j]
    Which is: '\xF5' (245)
Pixel mismatch at index 128 = (0, 4)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/7, where GetParam() = (32, 32, 0x107dab140) (0 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/8
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\xAA' (170)
  output_ref_[j]
    Which is: '\xA9' (169)
Pixel mismatch at index 268 = (12, 16)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/8, where GetParam() = (16, 34, 0x107dab140) (1 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/9
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\xF6' (246)
  output_ref_[j]
    Which is: '\xF5' (245)
Pixel mismatch at index 896 = (0, 28)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/9, where GetParam() = (32, 34, 0x107dab140) (1 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/10
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\x8C' (140)
  output_ref_[j]
    Which is: '\x8D' (141)
Pixel mismatch at index 376 = (56, 5)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/10, where GetParam() = (64, 34, 0x107dab140) (0 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/11
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\x9E' (158)
  output_ref_[j]
    Which is: '\xA0' (160)
Pixel mismatch at index 76 = (4, 9)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/11, where GetParam() = (8, 17, 0x107dab140) (0 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/12
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\xD5' (213)
  output_ref_[j]
    Which is: '\xD6' (214)
Pixel mismatch at index 112 = (0, 7)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/12, where GetParam() = (16, 17, 0x107dab140) (0 ms)
[ RUN      ] AV1/AV1WienerConvolveLbdTest.run_random_test/13
/Users/yons/work/SVT-AV1/test/weiner_convolve_test.cc:261: Failure
Expected equality of these values:
  output_tst_[j]
    Which is: '\xBB' (187)
  output_ref_[j]
    Which is: '\xBA' (186)
Pixel mismatch at index 75 = (11, 2)
[  FAILED  ] AV1/AV1WienerConvolveLbdTest.run_random_test/13, where GetParam() = (32, 17, 0x107dab140) (1 ms)
```
target function: 
`eb_av1_wiener_convolve_add_src_avx2`

It's probably caused by the rounding or clamp.

**Comment by ttrigui** [comment]
I believe this issue was fixed. I was not able to reproduce it in the latest master.
@Cidana-Developers can you please double check it?

**Comment by Cidana-Developers** [comment]
Seems like it still exists in commit 8e4cf49fa913bc0b7d0f92bd1342f589e281c639

**Comment by ttrigui** [comment]
> Seems like it still exists in commit [8e4cf49](https://github.com/OpenVisualCloud/SVT-AV1/commit/8e4cf49fa913bc0b7d0f92bd1342f589e281c639)

Correct. Looking into it.

**Comment by JackZhouVCD** [comment]
to be fixed by #661
